# Generated by Django 5.1.3 on 2024-11-06 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_parking', models.CharField(max_length=100)),
                ('nombre_place', models.IntegerField()),
                ('statut', models.CharField(choices=[('libre', 'Libre'), ('occupé', 'Occupé')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_place', models.IntegerField(unique=True)),
                ('taille', models.CharField(max_length=20)),
                ('type_place', models.CharField(choices=[('mobylette', 'Mobylette'), ('voiture', 'Voiture'), ('camion', 'Camion')], max_length=10)),
                ('parking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='places', to='Park.parking')),
            ],
        ),
    ]
